"""DeltaCore: Primitives and benchmarks for adaptive neural state.

A modular, research-oriented toolkit for systems that adapt their internal
state during inference.
"""

from deltacore.memory import AssociativeMemory, FiveMemoryState, read
from deltacore.scans import (
    AdaptiveScanResult,
    AffineChunk,
    AffineScanMetadata,
    AffineScanOperator,
    ChunkedScanResult,
    SequentialScanResult,
    adaptive_scan,
    affine_prefix_scan,
    build_chunks,
    chunked_scan,
    delta_to_affine,
    prefix_scan_memory,
    run_chunk,
    sequential_scan,
)
from deltacore.stability import (
    BaseStabilityController,
    SafeDynamicsRateController,
    SafeStepSizeController,
    StabilityConstraintResult,
    UnconstrainedController,
)
from deltacore.updates import (
    AdaptiveDeltaRule,
    AdaptiveDeltaStepResult,
    ConstantStepSize,
    ControlFeatureExtractor,
    CoupledState,
    DeltaRule,
    DeltaStepResult,
    DynamicsMemory,
    ErrorConditionedStepSize,
    ErrorProportionalTargetGenerator,
    FiveMemoryConfig,
    FiveMemoryScanResult,
    FiveMemoryStepResult,
    FiveMemorySystem,
    HebbianRule,
    HebbianStepResult,
    InputConditionedStepSize,
    SelfReferentialScanResult,
    SelfReferentialStepResult,
    SelfReferentialSystem,
    StateConditionedStepSize,
    StepSizeController,
    TargetGenerator,
)

__version__ = "0.0.1.dev0"

__all__: list[str] = [
    "__version__",
    "AssociativeMemory",
    "FiveMemoryState",
    "read",
    "DeltaRule",
    "DeltaStepResult",
    "HebbianRule",
    "HebbianStepResult",
    "AdaptiveDeltaRule",
    "AdaptiveDeltaStepResult",
    "StepSizeController",
    "ConstantStepSize",
    "InputConditionedStepSize",
    "ErrorConditionedStepSize",
    "StateConditionedStepSize",
    "sequential_scan",
    "SequentialScanResult",
    "adaptive_scan",
    "AdaptiveScanResult",
    "DynamicsMemory",
    "CoupledState",
    "SelfReferentialStepResult",
    "SelfReferentialScanResult",
    "TargetGenerator",
    "ErrorProportionalTargetGenerator",
    "ControlFeatureExtractor",
    "SelfReferentialSystem",
    "FiveMemoryConfig",
    "FiveMemoryStepResult",
    "FiveMemoryScanResult",
    "FiveMemorySystem",
    "BaseStabilityController",
    "UnconstrainedController",
    "SafeStepSizeController",
    "SafeDynamicsRateController",
    "StabilityConstraintResult",
    "AffineScanOperator",
    "AffineScanMetadata",
    "delta_to_affine",
    "affine_prefix_scan",
    "prefix_scan_memory",
    "AffineChunk",
    "ChunkedScanResult",
    "build_chunks",
    "run_chunk",
    "chunked_scan",
]
