# ==============================================================================
# DeltaCore: deltacore/observatory/__init__.py
# DeltaCore Adaptive State Observatory package root.
# ==============================================================================

from deltacore.observatory.analysis import (
    RunComparisonResult,
    ShiftResponseResult,
    StabilityAnalysisResult,
    analyze_shift_response,
    analyze_stability_events,
    compare_runs,
    extract_dynamics_stability_trajectory,
    extract_dynamics_trajectory,
    extract_error_trajectory,
    extract_stability_trajectory,
    extract_state_trajectory,
    extract_step_size_trajectory,
    extract_update_trajectory,
)
from deltacore.observatory.events import TrajectoryEvent, extract_events
from deltacore.observatory.fingerprint import (
    StateTransitionFingerprint,
    compare_fingerprints,
    generate_fingerprint,
)
from deltacore.observatory.loader import (
    convert_baseline_trajectory,
    load_aggregate_result,
    load_artifact,
    load_run_result,
    load_trajectory,
)
from deltacore.observatory.phase_13_plots import (
    generate_all_phase_13_plots,
    plot_continuous_vs_reset_bo,
    plot_deltacore_vs_conv_bu,
    plot_memory_vs_dim_bt,
    plot_perf_vs_resolution_br,
    plot_realworld_error_over_time_bk,
    plot_runtime_vs_dim_bs,
    plot_safe_vs_fixed_delta_bp,
    plot_shift_recovery_bl,
    plot_spatial_permutation_control_bq,
    plot_state_norm_trajectory_bm,
    plot_state_update_energy_bn,
)
from deltacore.observatory.phase_16_plots import (
    generate_all_phase_16_plots,
    plot_adaptation_energy_vs_severity_da,
    plot_continuous_vs_reset_ct,
    plot_cross_domain_matrix_cx,
    plot_error_vs_severity_cq,
    plot_eta_trajectories_cr,
    plot_failure_boundary_map_cv,
    plot_noise_robustness_cw,
    plot_per_seed_differences_cy,
    plot_resource_metrics_vs_severity_db,
    plot_retention_trajectories_cu,
    plot_safety_margin_vs_severity_cs,
    plot_state_norm_severe_cz,
)
from deltacore.observatory.phase_18_plots import generate_all_phase_18_plots
from deltacore.observatory.plots import (
    generate_all_plots,
    plot_absolute_vs_relative_error,
    plot_accuracy_vs_directions,
    plot_chunk_size_difference,
    plot_comparative_recovery_curves,
    plot_directional_learning_rate_map,
    plot_directional_memory_activity_map,
    plot_directional_output_magnitude,
    plot_error_vs_time,
    plot_failure_step_distribution,
    plot_fused_spatial_output,
    plot_key_correlation_vs_error,
    plot_memory_norm_vs_time,
    plot_metric_vs_directional_route,
    plot_recovery_latency_vs_energy,
    plot_runtime_vs_chunk_size,
    plot_stability_margin_vs_time,
    plot_step_size_vs_time,
    plot_train_val_loss,
    plot_update_norm_vs_time,
    plot_validation_error_vs_chunk_size,
)
from deltacore.observatory.replay import (
    MetricComparison,
    ReplayResult,
    execute_replay,
    replay_run_result,
)
from deltacore.observatory.report import generate_observatory_report
from deltacore.observatory.schema import StateTrajectory, TrajectoryStep
from deltacore.observatory.spatiotemporal_plots import (
    plot_a1_b_a1_recovery_bb,
    plot_adaptation_energy_vs_perf_bh,
    plot_adaptation_negative_transfer_pareto_ay,
    plot_continuous_vs_reset_bj,
    plot_error_vs_state_adaptive_bc,
    plot_memory_vs_dim_bg,
    plot_perf_vs_dim_be,
    plot_retention_ablation_ba,
    plot_retention_trajectories_az,
    plot_runtime_vs_dim_bf,
    plot_safe_vs_unsafe_bi,
    plot_spatial_vs_shuffled_bd,
    plot_spatiotemporal_error_over_time_ax,
)

__all__ = [
    # Schema
    "TrajectoryStep",
    "StateTrajectory",
    # Loader
    "load_trajectory",
    "load_run_result",
    "load_aggregate_result",
    "load_artifact",
    "convert_baseline_trajectory",
    # Events
    "TrajectoryEvent",
    "extract_events",
    # Analysis
    "extract_error_trajectory",
    "extract_state_trajectory",
    "extract_dynamics_trajectory",
    "extract_update_trajectory",
    "extract_step_size_trajectory",
    "extract_stability_trajectory",
    "extract_dynamics_stability_trajectory",
    "ShiftResponseResult",
    "analyze_shift_response",
    "StabilityAnalysisResult",
    "analyze_stability_events",
    "RunComparisonResult",
    "compare_runs",
    # Fingerprint
    "StateTransitionFingerprint",
    "generate_fingerprint",
    "compare_fingerprints",
    # Plots
    "plot_error_vs_time",
    "plot_step_size_vs_time",
    "plot_memory_norm_vs_time",
    "plot_update_norm_vs_time",
    "plot_stability_margin_vs_time",
    "plot_comparative_recovery_curves",
    "plot_key_correlation_vs_error",
    "plot_recovery_latency_vs_energy",
    "plot_failure_step_distribution",
    "plot_directional_output_magnitude",
    "plot_directional_learning_rate_map",
    "plot_directional_memory_activity_map",
    "plot_fused_spatial_output",
    "plot_chunk_size_difference",
    "plot_train_val_loss",
    "plot_accuracy_vs_directions",
    "plot_validation_error_vs_chunk_size",
    "plot_runtime_vs_chunk_size",
    "plot_metric_vs_directional_route",
    "plot_absolute_vs_relative_error",
    "generate_all_plots",
    # Replay
    "MetricComparison",
    "ReplayResult",
    "execute_replay",
    "replay_run_result",
    # Report
    "generate_observatory_report",
    # Spatio-Temporal Plots (Phase 12)
    "plot_spatiotemporal_error_over_time_ax",
    "plot_adaptation_negative_transfer_pareto_ay",
    "plot_retention_trajectories_az",
    "plot_retention_ablation_ba",
    "plot_a1_b_a1_recovery_bb",
    "plot_error_vs_state_adaptive_bc",
    "plot_spatial_vs_shuffled_bd",
    "plot_perf_vs_dim_be",
    "plot_runtime_vs_dim_bf",
    "plot_memory_vs_dim_bg",
    "plot_adaptation_energy_vs_perf_bh",
    "plot_safe_vs_unsafe_bi",
    "plot_continuous_vs_reset_bj",
    # Spatio-Temporal Plots (Phase 13: BK through BU)
    "generate_all_phase_13_plots",
    "plot_realworld_error_over_time_bk",
    "plot_shift_recovery_bl",
    "plot_state_norm_trajectory_bm",
    "plot_state_update_energy_bn",
    "plot_continuous_vs_reset_bo",
    "plot_safe_vs_fixed_delta_bp",
    "plot_spatial_permutation_control_bq",
    "plot_perf_vs_resolution_br",
    "plot_runtime_vs_dim_bs",
    "plot_memory_vs_dim_bt",
    "plot_deltacore_vs_conv_bu",
    # Spatio-Temporal Plots (Phase 16: CQ through DB)
    "generate_all_phase_16_plots",
    "plot_error_vs_severity_cq",
    "plot_eta_trajectories_cr",
    "plot_safety_margin_vs_severity_cs",
    "plot_continuous_vs_reset_ct",
    "plot_retention_trajectories_cu",
    "plot_failure_boundary_map_cv",
    "plot_noise_robustness_cw",
    "plot_cross_domain_matrix_cx",
    "plot_per_seed_differences_cy",
    "plot_state_norm_severe_cz",
    "plot_adaptation_energy_vs_severity_da",
    "plot_resource_metrics_vs_severity_db",
    # Classification Plots (Phase 18)
    "generate_all_phase_18_plots",
]
